server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: imgfloat
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:sqlite:imgfloat.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      platform: sqlite
  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${TWITCH_CLIENT_ID}
            client-secret: ${TWITCH_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "${TWITCH_REDIRECT_URI:{baseUrl}/login/oauth2/code/twitch}"
            authorization-grant-type: authorization_code
            scope: ["user:read:email"]
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://api.twitch.tv/helix/users
            user-name-attribute: login

management:
  endpoints:
    web:
      exposure:
        include: health,info
